site_name: 2025.2 (GRUPO 4) - ID JOVEM 

repo_name: "ID JOVEM"
repo_url: "https://github.com/Requisitos-de-Software/2025.2-Grupo04"

theme:
  name: material
  palette:
    - scheme: default
      primary: deep blue
      accent: black
      background: black
      text: white
      code: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: deep blue
      accent: black
      background: black
      text: white
      code: white
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Poppins
    code: Inconsolata
  font_size:
    text: 16px
    code: 14px
  locale: pt_BR

user_color_mode_toggle: true

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
    

extra_css:
  - stylesheets/extra.css

nav:
  - Início: "index.md"
  - Planejamento: "index.md"
  - Apresentação: "index.md"
  - Pré-Rastreabilidade: "index.md"
  - Atas: "index.md"
  - Contribuição: "index.md"

#  - Guias:
     # - Guia de Contribuição: "guias/guia_de_contribuicao.md"

#  - Equipe:
      #- Gestão de Pareamentos: "equipe/gestao_de_pareamento.md"
#  - Atas:
      #AS ATAS PRECISAM SEGUIR ESSE PADRAO DE NOME:
      #- Ata do dia XX/XX/2025: "Atas/ata_reuniao_XX_XX_25.md"
      
  
#  - Lean Inception:
    #- Visão do Produto: 'Lean_Inception/Vis_prod.md'
    #- Objetivos do Produto: 'Lean_Inception/obj_prod.md'
    #- Personas: 'Lean_Inception/personas.md'


#  - Gestão do Projeto:
    #- Metodologias e Ferramentas: 'projeto/metodologias_e_ferramentas.md'
  
#  - Encerramento:
    #- Post Mortem: 'encerramento/post_mortem.md'