site_name: Identidade Jovem - ID Jovem

repo_name: "ID Jovem"
repo_url: "https://github.com/Requisitos-de-Software/2025.2-Grupo04"

theme:
  name: material
  logo: assets/Logo_IDJovem.svg
  favicon: assets/Logo_IDJovem.svg
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo escuro
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro

  font:
    text: Poppins
    code: Inconsolata

  features:
    - navigation.tabs
    - navigation.top

  locale: pt_BR

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md

  - Planejamento:
      - Aplicativo: Planejamentos/Aplicativo.md
      - Aplicativo Avaliado: Planejamentos/Aplicativos_Avaliados.md
      - Cronograma: Planejamentos/Cronograma.md
      - Ferramentas: Planejamentos/Ferramentas.md
      - Metodologias: Planejamentos/Metodologias.md
      

  - Encontros:
      - Reunião: Encontros/Reunião.md
      - Atas:
        - Ata 01 (01/09): Encontros/atas/ata_01_09.md
        - Ata 02 (07/09): Encontros/atas/ata_07_09.md
        - Ata 03 (08/09): Encontros/atas/ata_08_09.md
        - Ata 04 (15/09): Encontros/atas/ata_15_09.md
        - Ata 05 (22/09): Encontros/atas/ata_22_09.md
        - Ata 06 (23/09): Encontros/atas/ata_23_09.md
        
  - Entregas:
      - Entrega 01:
          - Pré-Rastreabilidade (RichPicture): Entregas/Entregas_01/RichPicture.md
          - Apresentação: Entregas/Entregas_01/apresentacao01.md
          - Verificação e inspeção: Entregas/Entregas_01/Entrega_01.md
          - Inspeção grupo n+1: Entregas/Entregas_01/inspecao01.md

      - Entrega 02:
          - Elicitação:
            - Perfil de Usuário: Entrega_02/Elicitação/Perfil_de_Usuário.md
            - Definição de Personas: Entrega_02/Elicitação/Definicao_de_Personas.md
            - Técnicas de Elicitação:
              - Introspecção: Entrega_02/Elicitação/Introspecao.md
              - Questionário: Entrega_02/Elicitação/Questionario.md
              - Brainstorming: Entrega_02/Elicitação/Brainstorming.md
              - Observação: Entrega_02/Elicitação/Observacao.md
            - Priorização: Entrega_02/Elicitação/Priorizacao.md
            - Requisitos Elicitados: Entrega_02/Elicitação/Requisitos_Elicitados.md
            
      - Entrega 03:
          - Modelagem:
            - Diagramas: Entregas/Entregas_03/Modelagem/Diagramas.md
            - Especificações: Entregas/Entregas_03/Modelagem/Especificacoes.md
          - Pós-Rastreabilidade:
            - Matriz de Rastreabilidade: Entregas/Entregas_03/Pós-Rastreabilidade/Matriz.md
            - Relatórios: Entregas/Entregas_03/Pós-Rastreabilidade/Relatorios.md

      - Entrega Final:
        - Conclusão: Entregas/Entrega-Final/Conclusao.md
        - Anexos: Entregas/Entrega-Final/Anexos.md

  - Elicitação: 
    - Perfil de Usuário: Elicitação/Perfil_de_Usuário.md
    - Personas: Elicitação/Definicao_de_Personas.md
    - Técnicas de Elicitação:
      - Introspecção: Elicitação/Introspecao.md
      - Questionário: Elicitação/Questionario.md
      - Brainstorming: Elicitação/Brainstorming.md
      - Observação: Elicitação/Observacao.md
    
    - Priorização:
      - $ 100: Elicitação/100_Pontos.md
      - First Things First: Elicitação/First_Things_First.md
      - Three Level Scale: Elicitação/Three_Level_Scale.md
    - Elicitação: Elicitação/Requisitos_Elicitados.md
    