site_name: Identidade Jovem - ID Jovem

repo_name: "ID Jovem"
repo_url: "https://github.com/Requisitos-de-Software/2025.2-Grupo04"

theme:
    name: material
    logo: assets/Logo_IDJovem.svg
    favicon: assets/Logo_IDJovem.svg
    palette:
        - scheme: default
          primary: custom
          accent: custom
          toggle:
              icon: material/weather-sunny
              name: Mudar para modo escuro
        - scheme: slate
          primary: custom
          accent: custom
          toggle:
              icon: material/weather-night
              name: Mudar para modo claro

    font:
        text: Poppins
        code: Inconsolata

    features:
        - navigation.tabs
        - navigation.top

    locale: pt_BR

plugins:
    - search

markdown_extensions:
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid

extra_css:
    - stylesheets/extra.css

nav:
    - Início: index.md

    - Planejamento:
          - Aplicativo: Planejamentos/Aplicativo.md
          - Aplicativo Avaliado: Planejamentos/Aplicativos_Avaliados.md
          - Cronograma: Planejamentos/Cronograma.md
          - Ferramentas: Planejamentos/Ferramentas.md
          - Metodologias: Planejamentos/Metodologias.md

    - Encontros:
          - Reunião: Encontros/Reunião.md
          - Atas:
                - Ata 01 (01/09): Encontros/atas/ata_01_09.md
                - Ata 02 (07/09): Encontros/atas/ata_07_09.md
                - Ata 03 (08/09): Encontros/atas/ata_08_09.md
                - Ata 04 (15/09): Encontros/atas/ata_15_09.md
                - Ata 05 (22/09): Encontros/atas/ata_22_09.md
                - Ata 06 (23/09): Encontros/atas/ata_23_09.md
                - Ata 07 (27/09): Encontros/atas/ata_27_09.md
                - Ata 08 (29/09): Encontros/atas/ata_29_09.md
                - Ata 09 (06/10): Encontros/atas/ata_08_10.md

    - Entregas:
          - Entrega 01:
                - Pré-Rastreabilidade (RichPicture): Entregas/Entregas_01/RichPicture.md
                - Apresentação: Entregas/Entregas_01/apresentacao01.md
                - Verificação e inspeção: Entregas/Entregas_01/Entrega_01.md
                - Inspeção grupo n+1: Entregas/Entregas_01/inspecao01.md
            

          - Entrega 02:
                - Apresentação: Entregas/Entregas_02/Apresentação.md 
                - Elicitação:
                      - Perfil de Usuário: Entregas/Entregas_02/Elicitacao/Perfil_de_Usuário.md
                      - Personas: Entregas/Entregas_02/Elicitacao/Definicao_de_Personas.md

                - Técnicas de Elicitação:
                      - Analise de Documentos: Entregas/Entregas_02/Elicitacao/Analise_de_Documentos.md
                      - Entrevista: Entregas/Entregas_02/Elicitacao/Entrevista.md
                      - Brainstorming: Entregas/Entregas_02/Elicitacao/Brainstorming.md
                      - Introspecção: Entregas/Entregas_02/Elicitacao/Introspecção.md
                      - Observação: Entregas/Entregas_02/Elicitacao/Observação.md
                      - Storytelling: Entregas/Entregas_02/Elicitacao/Storytelling.md
                     
                      - Requisitos Elicitados: Entregas/Entregas_02/Elicitacao/Requisitos_Elicitados.md

                - Priorização:
                      - Técnicas:
                            - In or Out: Entregas/Entregas_02/Priorização/Tecnicas/InorOut.md
                            - Moscow: Entregas/Entregas_02/Priorização/Tecnicas/Moscow.md
                            - $100: Entregas/Entregas_02/Priorização/Tecnicas/100_Dolars.md
                      - Decisão: Entregas/Entregas_02/Priorização/Decisao.md
                      - Guia: Entregas/Entregas_02/Priorização/Guia.md
                      - Tabela: Entregas/Entregas_02/Priorização/Tabela.md
                - Inspeção grupo n+1: Entregas/Entregas_02/Inspeção02.md

          - Entrega 03:
                - Modelagem:

                          - Especificação Suplementar: Entregas/Entregas_03/Modelagem/Especificacao_Suplementar.md
                          - Caso de Uso: Entregas/Entregas_03/Modelagem/Caso_de_uso.md
                          - Cenário: Entregas/Entregas_03/Modelagem/Cenarios.md
                          - Léxicos: Entregas/Entregas_03/Modelagem/Lexicos.md
                          - Requisitos Não Implementados: Entregas/Entregas_03/Modelagem/Requisitos_Implementados.md
                - Apresentação: Entregas/Entregas_03/Apresentação.md
            #- Entrega 04:
                #- Modelagem-II:
                              #- NFR Framework: Entregas/Entregas_03/Modelagem_II/NFR_Framework.md
                              #- Histórias de Usuário: Entregas/Entregas_03/Modelagem_II/Historias_de_Usuario.md
                              #- Product Backlog: Entregas/Entregas_03/Modelagem_II/Product_Backlog.md

          - Entrega Final:
                - Conclusão: Entregas/Entrega-Final/Conclusao.md
                - Anexos: Entregas/Entrega-Final/Anexos.md